### ISSUE TITLE
Repo is too large.

### ISSUE THREAD

**Issue by SOF3** [Ad5001/Spooky#1]
Dear @Ad5001
Regarding your 500 ISE issue, your repo failed to enable because it is too large. I regret to tell you that nothing will be done on behalf of Poggit to resolve your issue, although some alternatives will be provided below.

The problem originates from that Poggit refuses to download any repo zipballs greater than 10 MB: https://github.com/poggit/poggit/blob/a30f9a1f2b029c15c346b4842cf44d131e84aeaf/src/poggit/Config.php#L27

According to a quick analysis of your repo:

```bash
$ find -type f -exec wc -c {} +
 2166838 ./img/struct.jpeg
   14286 ./LICENSE.md
     131 ./plugin.yml
     465 ./README.md
    1373 ./resources/ghost_player_data.dat
18020622 ./resources/Spooky.mcpack
   14806 ./src/Ad5001/Spooky/entity/Ghost.php
    7978 ./src/Ad5001/Spooky/Main.php
    4752 ./src/Ad5001/Spooky/tasks/TickTask.php
    1132 ./timing
20232383 total
```

It seems that you are trying to ship an enormous resource pack file (or whatever it is called) with your plugin.

As Poggit is not designed to build plugins with such enormous resource files, your project is going to deplete Poggit's harddisk memory quickly, so I am afraid no extra repo size quota will be provided to you.

Instead, I would recommend you to store the resource pack file on a file storage truly designed for binary files (Git is designed for storing source code, not binaries. Better storages include Dropbox, or the **Release** attachments on GitHub, etc., whatever gives you an easy or direct link) and download it in the plugin when the plugin runs for the first time.

Sorry for the inconvenience caused. I hope your issue can be resolved before Halloween night comes!

Regards
SOFe
Poggit Administrator and Developer

**Comment by SOF3** [comment]
As a side note, Poggit will automatically delete the artifact phar if it is greater than 2 MB, so even if you manage to reduce the resource pack to less than 10 MB, but still greater than 2 MB, it will still not be building.

**Comment by Ad5001** [comment]
Oh ok. I see... I'll try to reduce the filesize.

**Comment by Ad5001** [comment]
This has been fixed and the plugin size is now over 61KB.
