### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Ad5001/Spooky#2]
[16:56:17] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::registerEnchantment()" (EXCEPTION) in "Spooky-master/src/Ad5001/Spooky/Main" at line 40
[16:56:17] [Server thread/DEBUG]: #0 src/pocketmine/plugin/PluginBase(90): Ad5001\Spooky\Main->onEnable()
[16:56:17] [Server thread/DEBUG]: #1 DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(125): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[16:56:17] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(610): FolderPluginLoader\FolderPluginLoader->enablePlugin(Ad5001\Spooky\Main object)
[16:56:17] [Server thread/DEBUG]: #3 src/pocketmine/Server(1944): pocketmine\plugin\PluginManager->enablePlugin(Ad5001\Spooky\Main object)
[16:56:17] [Server thread/DEBUG]: #4 src/pocketmine/Server(1930): pocketmine\Server->enablePlugin(Ad5001\Spooky\Main object)
[16:56:17] [Server thread/DEBUG]: #5 src/pocketmine/Server(1716): pocketmine\Server->enablePlugins(integer 1)
[16:56:17] [Server thread/DEBUG]: #6 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/pmmp/PocketMine-MP.phar/, string /root/pmmp/, string /root/pmmp/plugins/)
[16:56:17] [Server thread/DEBUG]: #7 /root/pmmp/PocketMine-MP.phar(1): require(string phar:///root/pmmp/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[16:56:17] [Server thread/INFO]: Disabling Spooky v1

**Comment by Ad5001** [comment]
Can you send me your PocketMine.phar? Which version are you using?

**Comment by BogdanMakarchuk** [comment]
github.com/pmmp/PocketMine-MP every day I update the kernel with github

**Comment by BogdanMakarchuk** [comment]
nice spam to log


.%d..,.Da.N..~t.2]...D.x7.....V......O.T.i.s}......V.z.....k.......|....Nq.ZhU...i...6..YI..~.%<E^..MK.6t.VR` n.|.......Ff.e.f.....F.V.m...~..*..\.......[.......v..I~..~X..<,......l....:+........{W..{{9.>^....Z}N3.A....O.....S].is......;.<.y......7.....7u..TS./4.PT....~}......V.k_.O..Tc..x..1..m...jrld...>.r.ce4....Go{.[.`#0.,...,....6...0..jBl!}...............?7..M]~t.'...v...I...P....$.KV.2.4*..Eu{..6.@*_5T.G.B...n........ECL..qj....i.....V..>......S..2.qHj.{..i...,.WN.J.J4..U.....v..._..Q....5Y.V}.6..u.4....ed`.......=Os..g..]....S...}[l..};.,........E..F.z.$......o.~=.a].........MV.US3.t1.5g....P......_..x..j.^.?......g<.._w...<.jq.0v.0.H`@.JU..u...^dS......_'E~.H%.Ve(.>c.$K...M.y.S.N......m@..p.k.v\ir..:.>..^F..^5..[..d.....70.....^T*..2@U*..m.J.n..GC.DQUY..Ot......g7i..C..........=...ZK..}......tz.C.o).........s.TQ\KzEq).s....Un...._..0_-|e.,a...vf~.....).>.^.Do~.N./.2LS...[MU.R....1.I....8o..9.0/c..ds..............s..v5..lUloBv.V..=..\..0......M..|.=e.39..o.a..c.J......Z)YI.})g.dW.......yv.......p.p..............Hq..,H..u4..iT[..&U*..oV.LS......;.....*.^K...g.#..........Y.6/.......".(.eRe.>.I..C..~...zh.Q?...yo....dW.KoS>.&.....;F.Q...M...Z~...W..uRD}2j7..o.....=.W....H..........d>[Qm..LW)u.\WE6'..9Y...2...w...G.........y........>.k.R.........P0z...M(......UiV.......,........Qm..l.....P....r.O..~.Wf+..&......KO".k...u..*..w[....nL..>:.^...c...]..2O[..+......._.1^.k....}O.....U.{.9....Y...mp.RC..&8......8.k..3.&.b.P.;x...{.8.Y-...4O.....Yz.5./S_..R.m+...q.9........g.9.gU>....T'K.....0.u..0.l,Ad...H+V6. :z\.D1...C...O.......W`;.l...,..z.vI.lqI..r.......E*-.....9.-.m.!..w.t.+.....T'.hU.Q.....iu.....j..>.U)...|B7k%1.._.|.Q.....bd..z.95T5.e.G...SS#..,..t.by0.M.E".WqX...*.$.Zj.X..a._...~........<......U..kv...u6z...7oNs.....j?...0.P.....H".zAl5.L..~......80.;=..<..<..f.;....kq{...Q.5..M.|.].....d.6Q..f...ID$&.z.{Jx.......+....2.d.Z...d.....e.W.s!!.,,B^.....W......z.-..s..?....>L.......e. ..c..m*.E.@...[..-0.%c......#mAUUA.Tu.T.\......../h^V..j.M....a.Z.-.j.....Dad..DHXU%$......\*.Hg{...a........WWO.#a..R[.....OJ;l#?N..^.O_v.5w.....>...._...~..}.....!...u..Ob...q5.i5..dVs..._T4....]9j.P.~[....P.n.W.........Z......E..y.......4...4...@.^..Ld....c.0.%..g.m.L.y,..2.]...YU........0.D....K. ^g.@5..jb..{.._..O.....e0X..+..T(..^'I.vyNV...U..[.O.-.6M....m....E..r.'...Y....F..9.....B.%.Z.&.U.....W.....~.._t|.U.H.I..6....SlD.+\.6..Z.../......vq...S..Z.........."_....m0..].A.q.1....Ao......i".....{..f....B.\|..:.6.~..@...r..unf."...................Ho...h.z.....;Y.6.*..............#Yv...Z.4...d@..A......x.{)....@.....U..v...........h.\.BG:}.....}.zm).#.x...6.n.........$.t....U....Q.6.P...9......@....ji...@}.7W=J.\"..\.*1&.j:ew.7K..L.NN.3...4v....vd`....v.k.......K..Afk.gwmFKy...i.=.9...C}6...r.c....9.........C...$..NU!.......(.t+..U9....[ys.KZS.D.....t.eQ...~...[.....y...Y.......a:...-B......#S.Jo9....k. ...p..s......c".n.`.[...C.h..9K5...c.|.........P ./t...;..$A..>c.Y1._...*..<TH....x..M.q.....c.P.....f..#x.......2..I>..|....c...q..J..'.X...E..\.N[S.b.l.z.lm.,.....|.a...p@._.Zo.....{..N.r...........s....\.l.......c...9o..^.q..d.O.......r.}.g.g.......o..1.x.I..).k.]..x....)...J.9........?.C..[....~N...._.2wU8H.A..JRulh.F..Z#.vl}........N..fr.+g.Qh.u....A.._|./...;..N.{-.hJ.....'.1........W.%#.J.....A..O......D...X...BE.............%4.=@./..w.P...@..V..o}V....9".a.....@56.#\liz.......A..S......./........p>Z..z...z...........Q..L...D....P.S6...u....~|.g.t(O.jrR?x3.]?.......:3..(>.....<....k........a.p..........OUg...q.k..=.9.4..z......[jKo..=.s~.^..N.^m$.....VOa.,n..A..v.l..8n....d........t.._...%....j..{j.S.D..!....yS.G.Z..w..D.... .....7.a....~.....~P\.ja.^2...Q..a..B..b..{|O).=.:..CL..h...n.=&.9..o*......?...o.<v...zlz;.S.....x.j..7.4.f..;...Y...sM......~..}......r.v.....w...[.]......!s......`..5.i........1...Q.}~.z.......M&@[).@.#Tw....3...F.M..fW....O..|). .......,.F...TP..\..$.-#................gIF.06=........:kccK..%.a.>Y.q.C...y.(......KC.>.....:......T.I..T..>...fh........h.@...j.[....I..q'd..U....w...*R.$.y......i..l.....RC&.~.'G{.L.R2..<..y.........(..@.....@8..s|.b...d.a.....|.3_..f.(.....i%...=M3..Z2...K]..~.?.8....rM.rf..A.c.....y...d..........|.4.......6,~..fi...#......_.T[II..[ ..x..o..-.@.E&.".kN2.L.c.H_.B.K.......3w$.<g.$.d^(X.6.M.:......mzC.`{Z...*U..L.z.2F./.....Ho.H5%....4.^...fS.(xAN....'.../.9.-0,.X&#S.........=..bV..(.h].V.T{...oo=...VX][...Z..O...+..? ..:........^...g......\..........s....m.S....!g.Yu..7.n..S...s..d...n=.G..................n............oAS....wP6j..........c..n...T.- r.N.@..v.L.....5.+T.q.?..@.L)pY4...u..a.N_...}d.EO......0i..a_A -H6........S. .....Cb..j..$GBA........&.......p...........n..7HKY..m*)WU.!@;.g.Ze:L.6....[m...........~...#a.`.<..7^.C/..N.....V..7N_..Bs)Ye......5.......q.u........AF........d5.Ir`........W......H.x.....ET........O..?..U.;9.6s.l..`.t.......2$...y,....Q...../!Ri...TdqB........._..c_nc...q.v......j.l.g........3..:...T..<Z....P.K>.D>U.t.i..qh.$I.,..>...%WB..eET......KA.b.0...n.z..e.Xf.4U..P.I.6....>......w..+.7.Y...Q.C5...Y=../G...................E.w.UW.......n.r.3L....d....f...... r....d.e#(......AvT.-..M..4..U...g..3.......k..B....3...}.....Cj.p...m..br...k.&.@.%..`...4^Yu..........~.h......B....x...........\.N.w.Y.....0 $,_...^..#.B9....PIK]]... .:....Q.1..2....*.~...f..(Z..........i..a\..&.u7...,%5........,.P.....iI...naz|W.6f.;lh.h;.....8._..V....dW.6...0d...dn...}zT...O...x..B... .T(..t.U.2..$)..S.q.}.........y5d..l.|.y....O.k......V=..N...^/.....6g..3y...+....`d..z*..%.{....O.B........U.L..`.81i.e........%..;.R.;...........N.^X.x._...l.~.V.a....".....H.`.~*.dY..,....^mQ...OggS..........A."........4l.A.F.G.B...A.>.5.F.D.9.2.B.-.2.).=.3.:3:6MVG=NGORMPM.=.I.;.;.A.8.@.<.7.:.*.'.8;MJKQOQJ.G.B.;.=.@.@.F?7>;PTM?^...e..(._F.......X.).......]b.....PUb!Y..x1.k'h.I......Ma$..)..aw......}.(.g.....,.b..x..O..n..}/.n.{4f.7c..6o.M......3.z..wl."7.=4.%.....>.JZy...9..q.>.%y%...Y...0..8U........g~'.n.a?.g.......n...]5W._.l..m.......r...l.....>./.c....Q^k..5..Uy.%#,.1......!.qW-Z..)..G.........9.).-}............ .#..B.9......&I....U........epa.|".%..0..J.........,...!.VUu...,....d.j3.._....eX..z.......1.....M}3.U......9.._....&OMO%i...9.....=}.........-..~.m.sq..]....'.t..t......z~.......].A......M..Zk..]mu.../.4.......>....C..a.|hZ..i.I6...%......L.fU..E..v.QSh.aM....I"!U..vx\.....d%...._.edl2\.".,..N.....e.'.e.......T..J......H."O_>U.J...RWM%z.....2lP..~+&4.V..H...r.\1.E.V...r.O..S.].'a.C..:].96 .....x?=..GA2..D..a...8..q.s.a..../..].W...N..C...a48^..'o..Q9.o.Y......dG#.r...?..'....p_.9.O.s..q=.|7..b...L..Ee.....N..d.r...i....[..z.==UP.Y...?X...s.......c..._M3......k.......7.`..V....F.@..2.8..2.....|...j-.`.K26....,k.....5.B.....(U..c..../.u)].i....M.......m.._....U./r.....<..h......0,..*.......'...,.0$%CB.......VO....[b..6.j1.^.....=.FR=Lj.k.....C.RO,.C.7....zmsA...c7..~.fW.;mu......Nf."......p.&.c<;.2.....SL.d/tg.D.4C3IE...2.%Et.........j7...e..k...L7M...=...M{.i.E............_.....o.#3..ELJ.....J..+*......._...I............."....':krR..2..._.GQ..=z.......e....pY.....V".._r.x..6.....X..|.G..F.]~...:.....p.6.d..Q.,4.ICUb.....X..X.0.y...^.......}.oA..w.M.sRE....c.N..QI....,..........9.......=.......bY.:S.3....9c......".C..p......Q..z.hm..1.........z...F;.ak....u7.P..M....1.HDT.Z.W.v..crs..b..\..4.d$..#Q.u>.$..k.......Mxy..... ..q"...X..B.:Jw..1....D%%_.....J..,.2.........P....F..V..^ln.)!..CNTln.)a.p..7..........HUU....*F...w.>.+j..x...{Zq..t9d.w^......K..-...4y..sY..w.T.....J.....y..yg...-SqQ....yy...{...KF.?o.......a.....z;}...y...u..s~.M...+u..r[.s..L..9...ep......9..`..s..s^...#)X.......@Q....Z...u'nh....i.j......^....../}.p....jyu_.~m.....+c......j.*....x...z........?.}.......l.j7..T.r.J.r...\N.....x...U.05....Q...d....2zf.*VUD.A...}Y.4..!.........R|.]..N.................r..|...f.^.K......!..g......}....w....i.v......D......?....../.}X..~.T......a..c.gY...q...uBgw.t=.v....2.I..v..f..hq............m$.&_S.....X.~IM..'.o.Y.y4....20..).=..W.....%;.pV...aOq...MV>7&I.....(.....TR.I..?+.o..k...........-.,_....k....I......eAv5h.x~..n......B...j....(&.7C.n...(.v..}4.........c.=..F............x.YC.\..t..3.}..............| .4y...8.2c.....+...'.4M.dN...r8.=..K........d....S..q.{2...>....hP..j.q.>.g:..K._f6c....I..J.?.. .%.xl.zv.<..+.M........Q......te{6.`..u.d$.. ..E./d0.,m....v.....n.B..m.:....$=.}.........sd...-..>|....(`1A......H*...?...m.D......'..K.&.(...c...........m}OF..&...J-..04...I...!C../....b..........n.......%<......s...v......N.4..).k....Z.ok..XGy_ G.....G........a..j.+....?oV.

**Comment by robske110** [comment]
@BogdanMakarchuk that issue is fixed in #3

**Comment by BogdanMakarchuk** [comment]
@robske110 after update

**Comment by Ad5001** [comment]
@BogdanMakarchuk Wym?

**Comment by Ad5001** [comment]
Is this error still happening?

**Comment by BogdanMakarchuk** [comment]
error with enchantment is no longer there, but I do not know about spam

**Comment by Ad5001** [comment]
Haven't seen it in a while. Just reopen this issue if you re see it.
